name: kawtharuna
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.4+4

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
#  intl:

  just_audio: ^0.9.17
  audio_service: ^0.18.12

  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  animations: ^2.0.10

  logging: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13

  # If you don't need one of the following dependencies,
  # delete the relevant line below, and get rid of any Dart code
  # that references the dependency.
  firebase_core: ^2.1.1  # Needed for Crashlytics below
  firebase_crashlytics: ^3.4.8
  firebase_performance: ^0.9.3+8


  games_services: ^3.0.0  # Achievements and leaderboards
  google_mobile_ads: ^2.0.1  # Ads
  in_app_purchase: ^3.0.1  # In-app purchases
  cloud_firestore: ^4.4.4
  get_it: ^7.2.0
  injectable: ^2.1.0
  device_info_plus: ^8.1.0
  google_fonts: ^4.0.3
  flex_color_scheme: ^7.3.1
  internet_connection_checker: ^1.0.0+1

  dio: ^5.3.0
  # Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.3.1

  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  fluttertoast: ^8.2.1

  devicelocale: ^0.6.0
  http_parser: ^4.0.2
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.3
  rxdart: ^0.27.7
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0


  # A lightweight flutter package to simplify the creation of a miniplayer by providing a builder
  # function with the current height and percentage progress. The widget responds to tap and drag
  # gestures and is highly customizable. What is a miniplayer? Miniplayers are commonly used in
  # media applications like Spotify and Youtube. A miniplayer can be expanded and minified and
  # remains on the screen when minified until dismissed by the user. See the demo below for
  # an example.
  miniplayer: ^1.0.1
  cached_network_image: ^3.3.0
  firebase_storage: ^11.0.16

  # A flexible widget for user notification.
  # Customize your text, button, duration, animations and much more.
  # For Android devs, it is made to replace Snackbars and Toasts.
  another_flushbar: ^1.12.29


#  flutter pub upgrade --major-versions

dependency_overrides:
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  analysis_defaults:
    path: ./analysis_defaults
  test: ^1.19.0

  flutter_launcher_icons: ^0.13.1


  # Change App Package Name with single command. It makes the process very easy and fast.
  #  flutter pub run change_app_package_name:main com.kawtharuna.mobile
  change_app_package_name: ^1.1.0


  # It helps you to change your flutter project's AppName and BundleId for different platforms,
  # currently only available for IOS, Android, macOS, Windows and Web
  # flutter pub global activate rename
  # flutter pub global deactivate rename
  # flutter pub global run rename --appname "Kawtharuna"
  # rename setAppName --value "Kawtharuna"

  rename: ^3.0.1

  # When your app is opened, there is a brief time while the native app loads Flutter. By default,
  # during this time, the native app displays a white splash screen. This package automatically
  # generates iOS, Android, and Web-native code for customizing this native splash screen background
  # color and splash image. Supports dark mode, full screen, and platform-specific options.
  flutter_native_splash: ^2.2.19


  # The Flutter code generator for your assets, fonts, colors,
  # … — Get rid of all String-based APIs.
  injectable_generator: ^2.1.4
  analyzer: ^5.2.0
  #  json_serializable: ^3.2.2
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

  flutter_gen_runner: ^5.2.0
  flutter_gen: ^5.3.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/music/
    - assets/Permanent_Marker/
    - assets/sfx/
    - assets/reciters/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf


flutter_gen:
  output: lib/src/core/generated_files/assets/

  line_length: 80
  null_safety: true
  style: snake-case
  integrations:
    flutter_svg: true
  assets:
    enabled: true
  fonts:
    enabled: false

#  # Optional
#  integrations:
#    flutter_svg: true
#    flare_flutter: true
#    rive: true
#    lottie: true

#  colors:
#    inputs:
#      - assets/color/colors.xml


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_launcher.png"
  #  adaptive_icon_background: "#FFFFFF"
  #  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  web:
    generate: true
    #    image_path: "path/to/image.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/app_launcher.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_launcher.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_launcher.png
  #  branding: assets/icon.png
  color_dark: "#121212"
  image_dark: assets/images/app_launcher.png
  #  branding_dark: assets/icon.png

  android_12:
    image: assets/images/app_launcher.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/app_launcher.png
    icon_background_color_dark: "#121212"

  web: false


# flutter_scripts run
# dart pub global deactivate flutter_scripts
# dart pub global activate flutter_scripts
scripts:
  # dev environment:
  run-dev: flutter clean && flutter pub get && flutter run --dart-define ENV=dev --flavor=dev
  build-dev: flutter clean && flutter pub get && flutter build apk --dart-define ENV=dev --flavor=dev

  # prod environment:
  run-prod: flutter clean && flutter pub get && flutter run --dart-define ENV=prod --flavor=prod
  run-release-prod: flutter clean && flutter pub get && flutter run --release --dart-define ENV=prod --flavor=prod
  build-app-prod: flutter clean && flutter pub get && flutter build apk --dart-define ENV=prod --flavor=prod
  build-bundle-prod: flutter clean && flutter pub get && flutter build appbundle --release --dart-define ENV=prod --flavor=prod

  # development scripts:
  generate_files: flutter packages get && flutter pub run build_runner build --delete-conflicting-outputs
  clean_generate_files: flutter clean && flutter packages get && flutter pub run build_runner build --delete-conflicting-outputs
  generate_watch_files:  flutter packages get && flutter pub run build_runner watch --delete-conflicting-outputs

  generate_app_logo: flutter clean && flutter packages get && flutter pub run flutter_launcher_icons
  generate_splash: flutter clean && flutter packages get && flutter pub run flutter_native_splash:create

  cache_repair: flutter clean && flutter pub cache repair && flutter pub run build_runner clean
  install_activate_flutter_gen: brew install FlutterGen/tap/fluttergen && dart pub global activate flutter_gen && flutter pub get && flutter packages pub run build_runner build

flutter_intl:
  enabled: true
  main_local: en
  class_name: Translations
  arb_dir: lib/src/core/managers/localization/res
  output_dir: lib/src/core/managers/localization/generated
